#!/usr/bin/env python3
"""
public_extraction_filter.py — generate EXCLUDE list for a public-extraction repo.

Scans `master-brain/decisions/*.md` frontmatter; emits paths whose status is
`superseded` / `awaiting-operator-decision` / `proposal` / `closed` / `parked`.
Public extraction tooling reads this list to exclude internal indecision +
historical-only docs from the public release.

Usage:
  public_extraction_filter.py [--root <path>] [--format list|json|markdown]
  public_extraction_filter.py --check <path>   # exit 0 if INCLUDE, 1 if EXCLUDE

Reversible: pure read; never mutates state. Delete file to roll back.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

WORKSPACE_DEFAULT = Path(__file__).resolve().parents[4]
EXCLUDE_STATUSES = {
    "superseded",
    "awaiting-operator-decision",
    "awaiting-decision",
    "proposal",
    "draft",
    "parked",
}
# "closed" is INCLUDED — closed work is historical-but-load-bearing (e.g., F7
# retrospective closure). "active" / "locked" / "landed" always INCLUDED.

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
STATUS_RE = re.compile(r"^status:\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)


def extract_status(text: str) -> str | None:
    """Return frontmatter `status:` value, or None if no frontmatter / no status."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    s = STATUS_RE.search(m.group(1))
    if not s:
        return None
    return s.group(1).strip().lower().strip('"').strip("'")


def should_exclude(path: Path) -> tuple[bool, str]:
    """Return (excluded?, reason)."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return False, f"read-error:{e}"
    status = extract_status(text)
    if status is None:
        return False, "no-frontmatter-status (defaults to INCLUDE)"
    if status in EXCLUDE_STATUSES:
        return True, f"status={status}"
    return False, f"status={status}"


def scan(root: Path) -> list[tuple[Path, bool, str]]:
    decisions_dir = root / "master-brain" / "decisions"
    if not decisions_dir.exists():
        print(f"[ERROR] decisions dir missing: {decisions_dir}", file=sys.stderr)
        sys.exit(2)
    results: list[tuple[Path, bool, str]] = []
    for p in sorted(decisions_dir.glob("*.md")):
        if p.name == "decisions.md":  # index file, always include
            continue
        excluded, reason = should_exclude(p)
        results.append((p, excluded, reason))
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=WORKSPACE_DEFAULT,
                        help="workspace root (auto-detect from script path)")
    parser.add_argument("--format", choices=["list", "json", "markdown"], default="list",
                        help="output format")
    parser.add_argument("--check", type=Path, default=None,
                        help="single-file check; exit 0=INCLUDE, 1=EXCLUDE")
    args = parser.parse_args()

    if args.check:
        excluded, reason = should_exclude(args.check)
        verdict = "EXCLUDE" if excluded else "INCLUDE"
        print(f"{verdict}: {args.check} ({reason})")
        return 1 if excluded else 0

    results = scan(args.root)
    excluded = [(p, r) for p, e, r in results if e]
    included = [(p, r) for p, e, r in results if not e]

    if args.format == "list":
        print(f"# Excluded ({len(excluded)} of {len(results)}):")
        for p, r in excluded:
            print(f"{p.relative_to(args.root)}  # {r}")
    elif args.format == "json":
        print(json.dumps({
            "scanned": len(results),
            "excluded_count": len(excluded),
            "included_count": len(included),
            "excluded": [{"path": str(p.relative_to(args.root)), "reason": r} for p, r in excluded],
        }, indent=2))
    elif args.format == "markdown":
        print(f"# Public extraction EXCLUDE list\n")
        print(f"*Generated by `public_extraction_filter.py`. {len(excluded)} of {len(results)} decision docs excluded from `cerebro-doctrine` Apache-2.0 release.*\n")
        print("| Path | Status |")
        print("|---|---|")
        for p, r in excluded:
            print(f"| `{p.relative_to(args.root)}` | {r} |")

    return 0


if __name__ == "__main__":
    sys.exit(main())
