#!/usr/bin/env bash
# skill-status.sh — render the Libro skill-status registry.
#
# Joins three sources:
#   1. skills/            — the skill folders actually present (ground truth)
#   2. manifests/*.json   — which profiles include each skill (source of truth)
#   3. skill-status.json  — maturity status + summary overlay (the only hand-edited file)
#
# Emits a markdown table. With --write, writes SKILL_STATUS.md at repo root.
# Drift guard: a skill folder with no status entry, or a status entry with no
# folder, is reported as a WARNING (non-zero hint in the table) so the registry
# stays in lockstep with what ships.
#
# Usage:
#   bash scripts/skill-status.sh            # print table to stdout
#   bash scripts/skill-status.sh --write    # also write SKILL_STATUS.md
#
# No dependencies beyond bash + python3 (stdlib only).

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Repo root = parent of scripts/. Works in both the public repo (flat) and the
# workspace source tree (products/libro-packaging/).
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WRITE=0
[[ "${1:-}" == "--write" ]] && WRITE=1

python3 - "$ROOT" "$WRITE" <<'PYEOF'
import json, os, sys

root, write = sys.argv[1], sys.argv[2] == "1"
skills_dir = os.path.join(root, "skills")
manifests_dir = os.path.join(root, "manifests")
overlay_path = os.path.join(root, "skill-status.json")

# 1. Folders present.
present = sorted(
    d for d in os.listdir(skills_dir)
    if os.path.isdir(os.path.join(skills_dir, d))
) if os.path.isdir(skills_dir) else []

# 2. Profile membership from manifests.
profiles = {}  # skill -> set(profile)
if os.path.isdir(manifests_dir):
    for fn in os.listdir(manifests_dir):
        if not fn.endswith(".json"):
            continue
        prof = fn[:-5]
        try:
            d = json.load(open(os.path.join(manifests_dir, fn)))
        except Exception:
            continue
        for s in d.get("additive_modules", {}).get("skills", []):
            profiles.setdefault(s, set()).add(prof)

# 3. Status overlay.
overlay = {}
legend = {}
if os.path.isfile(overlay_path):
    o = json.load(open(overlay_path))
    overlay = o.get("skills", {})
    legend = o.get("_status_legend", {})

warnings = []
rows = []
for s in present:
    ov = overlay.get(s)
    if ov is None:
        warnings.append(f"skill '{s}' present but missing from skill-status.json")
        status, summary = "UNLISTED", ""
    else:
        status, summary = ov.get("status", "UNLISTED"), ov.get("summary", "")
    profs = profiles.get(s, set())
    prof_str = "core" if "libro-core" in profs else (", ".join(sorted(p.replace("libro-", "") for p in profs)) or "—")
    rows.append((s, status, prof_str, summary))

for s in overlay:
    if s not in present:
        warnings.append(f"skill '{s}' in skill-status.json but no folder in skills/")

# Render markdown.
out = []
out.append("# Libro skill status")
out.append("")
out.append("Which shipped skills are safe to rely on, and which are preview. "
           "Generated by `scripts/skill-status.sh` — do not edit by hand "
           "(edit `skill-status.json` and regenerate).")
out.append("")
if legend:
    out.append("**Status legend**")
    out.append("")
    for k in ("stable", "preview", "experimental"):
        if k in legend:
            out.append(f"- **{k}** — {legend[k]}")
    out.append("")
out.append("| Skill | Status | Profiles | What it does |")
out.append("|---|---|---|---|")
badge = {"stable": "🟢 stable", "preview": "🟡 preview", "experimental": "🟠 experimental"}
for s, status, prof_str, summary in rows:
    out.append(f"| `{s}` | {badge.get(status, status)} | {prof_str} | {summary} |")
out.append("")
stable_n = sum(1 for r in rows if r[1] == "stable")
preview_n = sum(1 for r in rows if r[1] == "preview")
out.append(f"_{len(rows)} skills shipped · {stable_n} stable · {preview_n} preview._")
out.append("")

text = "\n".join(out)
print(text)

if warnings:
    sys.stderr.write("\n[skill-status] DRIFT WARNINGS:\n")
    for w in warnings:
        sys.stderr.write(f"  - {w}\n")

if write:
    dest = os.path.join(root, "SKILL_STATUS.md")
    open(dest, "w").write(text)
    sys.stderr.write(f"\n[skill-status] wrote {dest}\n")
PYEOF
